name: Echo Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Добавляем возможность запуска пайплайна вручную

jobs:
  echo_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo a message
        run: echo "Hello, world!"
        
      - name: Request test run
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Laikovski/pytests
          event-type: run_tests
